/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#eceef0",
        "outline-variant": "#c2c6d3",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#005236",
        "on-background": "#191c1e",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-container": "#44d69b",
        "on-primary-fixed-variant": "#00468c",
        "on-tertiary-fixed": "#002113",
        "surface-tint": "#245eaa",
        "background": "#f7f9fb",
        "on-surface": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#bcc7de",
        "inverse-primary": "#a9c7ff",
        "error": "#ba1a1a",
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "primary": "#00366e",
        "error-container": "#ffdad6",
        "primary-fixed": "#d6e3ff",
        "tertiary": "#003f29",
        "on-primary": "#ffffff",
        "on-secondary-container": "#586377",
        "tertiary-container": "#00593c",
        "on-error-container": "#93000a",
        "surface-dim": "#d8dadc",
        "on-secondary-fixed": "#111c2d",
        "on-secondary-fixed-variant": "#3c475a",
        "primary-container": "#004c97",
        "surface": "#f7f9fb",
        "on-surface-variant": "#424751",
        "inverse-on-surface": "#eff1f3",
        "on-error": "#ffffff",
        "secondary-fixed": "#d8e3fb",
        "tertiary-fixed": "#6ffbbe",
        "on-primary-fixed": "#001b3d",
        "primary-fixed-dim": "#a9c7ff",
        "surface-container-high": "#e6e8ea",
        "inverse-surface": "#2d3133",
        "tertiary-fixed-dim": "#4edea3",
        "outline": "#737782",
        "secondary-container": "#d5e0f8",
        "on-secondary": "#ffffff",
        "secondary": "#545f73",
        "surface-variant": "#e0e3e5",
        "on-primary-container": "#9bbfff",
        
        "status-opener-bg": "rgba(16, 185, 129, 0.15)",
        "status-opener-text": "#059669",
        "status-closer-bg": "rgba(249, 115, 22, 0.15)",
        "status-closer-text": "#ea580c",
        "status-overnight-bg": "rgba(139, 92, 246, 0.15)",
        "status-overnight-text": "#7c3aed",
        "status-mid-bg": "rgba(59, 130, 246, 0.15)",
        "status-mid-text": "#2563eb",
        "status-violation-bg": "rgba(239, 68, 68, 0.15)",
        "status-violation-text": "#dc2626",
        "status-rto-bg": "rgba(217, 70, 239, 0.15)",
        "status-rto-text": "#c026d3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "2rem",
        "stack-default": "1rem",
        "gutter": "1rem",
        "margin-mobile": "1rem",
        "stack-dense": "0.5rem",
        "container-max": "1440px"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "data-tabular": ["Inter"],
        "label-bold": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-md": ["Inter"]
      },
      fontSize: {
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "data-tabular": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "label-bold": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
